name: CD Mock service

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on:
      group: mock

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: deploy
        run: |
          sudo systemctl restart http-mock
          echo "deploy done for test"
